### ISSUE TITLE
TrunkAddressingModify

### ISSUE THREAD

**Issue by kikohnl** [nigelm/broadworks_ocip#11]
* Broadworks OCI-P Interface version: 2.0.3
* Python version: 3.8.10
* Operating System: Ubuntu 20.04.4 LTS

### Description

move a TN to an entererprise trunking number.

### What I Did

```
#!/usr/bin/env python3
import argparse
import csv

from broadworks_ocip import BroadworksAPI
from broadworks_ocip.exceptions import OCIErrorResponse

# Authenitcaion parameters
#

BASIC_API_PARAMS_LAB = {
    "host": "lab-web.voip.hawaiiantel.net",
    "username": "Username",
    "password": "password!",
    "port": 2208,
}

# configure the API, connect and authenticate to the server
api = BroadworksAPI(**BASIC_API_PARAMS_LAB)

# testing
def UserModifyRequest21(user, trunk):
    try:
        api.command('UserModifyRequest21', user_id = user,
            trunk_group_device_endpoint=api.get_type_object("TrunkAddressingModify", enterprise_trunk_name = trunk))
        
        return True

    except OCIErrorResponse as err:
        print("Unable to modify enterprise trunk {} for user {}, Error is {}".format(trunk, user, err.message))

def main():
    
    parser = argparse.ArgumentParser(prog = "chget", description="change the user to a Enterprise Trunk user")
    parser.add_argument('-f', "--file",  help="optional file of TNs to process", action='store', dest='file')
    parser.add_argument("-e","--trunk", help="enterprise trunk", action='store', dest='trunk')

    args = parser.parse_args()
    
    trunk=args.trunk
    fn=args.file

    with open(fn) as csv_file:

        csv_reader = csv.reader(csv_file,delimiter=',')
        line_count = 0

        for row in csv_reader:
            if line_count == 0:
                print(f'Column names are {", ".join(row)}')
                line_count +=1
            else:                
                print(row)
                user=row[0].strip()
                print("About to change {}, to et {}\n".format(user, trunk))
                line_count +=1
                result = UserModifyRequest21(user, trunk)
                if result==True:
                    print("Unable to modify enterprise trunk {} for user {}".format(user, trunk))

    #take out line for header row
    line_count=line_count-1

    print('Processed {} lines.\n'.format(line_count)) 


if __name__ == "__main__":
    main()

If there was a crash, please include the traceback here.
```
raise OCIErrorUnexpectedAttribute(
broadworks_ocip.exceptions.OCIErrorUnexpectedAttribute: OCIErrorUnexpectedAttribute(UserModifyRequest21: Unexpected attribute(s) dict_keys(['trunk_group_device_endpoint']))

**Comment by nigelm** [comment]
`UserModifyRequest21` has no parameter or attribute called `trunk_group_device_endpoint`

`UserAddRequest14` does have a parameter or attribute called `trunk_group_device_endpoint` but that is not of type `TrunkAddressingModify` (which is not a type used by any non-deprecated item in current Broadworks).

I have no idea what you are trying to do here...

**Comment by kikohnl** [comment]
UserModifyRequest21 has endpoint which can be many thinks, it's marked as a comment unknown.

I my old Go programs, that don't work any more I did:

**Comment by kikohnl** [comment]
here is what the Go program did:
                var tnMod = new(UserModifyRequest21)
                tnMod.UserID = fmt.Sprintf("%s", line[:10])
                tnMod.Endpoint = new(endpoint)
                tnMod.Endpoint.TrunkAddressing = new(trunkAddressing)
                tnMod.Endpoint.TrunkAddressing.EnterpriseTrunkName = ETrunk

type endpoint struct {
        TrunkAddressing      *trunkAddressing      `xml:"trunkAddressing,omitempty"`
        AccessDeviceEndpoint *accessDeviceEndpoint `xml:"accessDeviceEndpoint,omitempty"`
}

type trunkAddressing struct {
        TrunkGroupDeviceEndpoint string `xml:"trunkGroupDeviceEndpoint,omitempty"`
        EnterpriseTrunkName      string `xml:"enterpriseTrunkName,omitempty"`
        AlternateTrunkIdentity   string `xml:"alternateTrunkIdentity,omitempty"`
}

type accessDeviceEndpoint struct {
        AccessDevice    string `xml:"accessDevice,omitempty"`
        LinePort        string `xml:"linePort,omitempty"`
        PrivateIdentity string `xml:"privateIdentity,omitempty"`
        ContactList     string `xml:"contactList,omitempty"`
        PortNumber      string `xml:"portNumber,omitempty"`
}
type UserModifyRequest21 struct {
*elided*
Endpoint                 *endpoint `xml:"endpoint,omitempty"`
*elided"
}

**Comment by kikohnl** [comment]
This is what I am trying to do, PSLog from XSP,  but endpoint seems to be unknown/undefined:

<?xml version="1.0" encoding="ISO-8859-1"?>
<BroadsoftDocument protocol="OCI" xmlns="C" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<userId xmlns="">LoginID</userId>
    <command xsi:type="UserModifyRequest22" xmlns="">
        <userId>7055551219</userId>
        <phoneNumber>7055551219</phoneNumber>
        <extension>1219</extension>
        <sipAliasList xsi:nil="true"/>
        <endpoint>
            <trunkAddressing>
                <trunkGroupDeviceEndpoint xsi:nil="true"/>
                    <enterpriseTrunkName>ET02</enterpriseTrunkName>
                    <alternateTrunkIdentity xsi:nil="true"/>
                    <physicalLocation xsi:nil="true"/>
            </trunkAddressing>
        </endpoint>
    </command>
</BroadsoftDocument>

**Comment by nigelm** [comment]
Looks like `UserModifyRequest21` has an `endpoint` which the schema parser has been unable to resolve into a type.

To be able to look at this I would need to see the resultant XML generated by that command.

**Comment by kikohnl** [comment]
<?xml version="1.0" encoding="ISO-8859-1"?>
<BroadsoftDocument protocol="OCI" xmlns="C" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><userId xmlns="">Keith.Otis.System</userId><command xsi:type="UserModifyRequest22" xmlns=""><
userId>7055551219</userId><phoneNumber>7055551219</phoneNumber><extension>1219</extension><sipAliasList xsi:nil="true"/><endpoint><trunkAddressing><trunkGroupDeviceEndpoint xsi:nil="true"/><e
nterpriseTrunkName>ET02</enterpriseTrunkName><alternateTrunkIdentity xsi:nil="true"/><physicalLocation xsi:nil="true"/></trunkAddressing></endpoint></command></BroadsoftDocument>

**Comment by nigelm** [comment]
ie the complete command XML (you can elide sensitive data within it, but the tags must all be there), at least including everything between:-

```
<command echo="" xsi:type="UserModifyRequest21" xmlns="">
...
</command>
```

**Comment by kikohnl** [comment]
`
[UserModifyRequest22.txt](https://github.com/nigelm/broadworks_ocip/files/8960717/UserModifyRequest22.txt)
`

**Comment by kikohnl** [comment]
From the R24 schema, OCISchemaUser.xsd UserModifyRequest22 show endpoint defined:
<xs:element name="endpoint" nillable="true" minOccurs="0">
            <xs:complexType>
              <xs:annotation/>
              <xs:choice>
                <xs:element name="accessDeviceEndpoint" type="AccessDeviceMultipleIdentityAndContactEndpointModify22"/>
                <xs:element name="trunkAddressing" type="TrunkAddressingMultipleContactModify22"/>
              </xs:choice>
            </xs:complexType>
          </xs:element>

**Comment by nigelm** [comment]
Have a look at this branch https://github.com/nigelm/broadworks_ocip/tree/nested_elements

I haven't as yet updated the documentation at all, but there are a couple of tests - look at the `*nested_elements*` tests in `test_basic_command_xml.py`

The other change is the addition of a Null (as in `from null_object import Null`) which can be used to force an element in XML to explicitly `nil` - ie likely in the UserModify stuff would be used to delete an attribute.

I need to work out how to write this up, likely to be a little while until I get it to a release state.

**Comment by kikohnl** [comment]
Good news:

`<BroadsoftDocument xmlns="C" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" protocol="OCI">
<userId xmlns="">Keith.Otis.System</userId>
    <command xmlns="" xsi:type="UserModifyRequest22">
        <userId>7055551219</userId>
        <sipAliasList xsi:nil="true"/>
        <endpoint>
            <trunkAddressing>
                <trunkGroupDeviceEndpoint xsi:nil="true"/>
                <enterpriseTrunkName>ET01</enterpriseTrunkName>
                <alternateTrunkIdentity xsi:nil="true"/>
            </trunkAddressing>
        </endpoint>
    </command>
</BroadsoftDocument>

<BroadsoftDocument protocol="OCI" xmlns="C" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<userId xmlns="">Keith.Otis.System</userId>
    <command echo="" xsi:type="c:SuccessResponse" xmlns:c="C" xmlns=""/>
</BroadsoftDocument>`

and the command is successful!
Thank  you!

**Comment by kikohnl** [comment]
```
This morning I was able to use the script to move 960 TNs in to an Enterprise Trunk and enable Calling name retrieval in 35 seconds.

This issue has been resolved.
