### ISSUE TITLE
GroupGetListInServiceProviderRequest no GroupTable in repsonse

### ISSUE THREAD

**Issue by kikohnl** [nigelm/broadworks_ocip#3]
* Broadworks OCI-P Interface version: R21SP1 and R24
* Python version: Python 3.8.5
* Operating System: Ubuntu 20.04.2 LTS

### Description

Describe what you were trying to get done.
Trying to walk Enterprises aka Service provider, get each group and disable international dialing and international call  forwarding.

Tell us what happened, what went wrong, and what you expected to happen.

Retriveing the Enterprises works as expected., get the groups in the enterprise does not.

### What I Did
#!/usr/bin/env python3
import argparse

from broadworks_ocip import BroadworksAPI

BASIC_API_PARAMS = {
    "host": "server.net",
    "username": "UserID",
    "password": Password",
    "port": 2208,
    "session_id": "00000000-1111-2222-3333-444444444444",
}
def main():

    api = BroadworksAPI(**BASIC_API_PARAMS)
    result = api.command("ServiceProviderGetListRequest")
    for thing in result.service_provider_table:
        print(thing.service_provider_id,thing.service_provider_name)

        groups = api.command("GroupGetListInServiceProviderRequest", service_provider_id=thing.service_provider_id )
        for group in groups.groupTable:
            print(group.groupTable)

if __name__ == "__main__":
    main()
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
python3 test-connect.py         
OhanaSelfStorage IZ190536
Traceback (most recent call last):
  File "test-connect.py", line 29, in <module>
    main()
  File "test-connect.py", line 24, in main
    for group in groups.groupTable:
  File "/home/kotis/.local/lib/python3.8/site-packages/classforge/classes.py", line 93, in __getattribute__
    return super(Class, self).__getattribute__(what)
AttributeError: 'GroupGetListInServiceProviderResponse' object has no attribute 'groupTable'

however the OCIP logging on the AS shows:

<?xml version="1.0" encoding="ISO-8859-1"?>
<BroadsoftDocument protocol="OCI" xmlns="C" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<userId xmlns="">USERIDHERE</userId>
  <command echo="" xsi:type="GroupGetListInServiceProviderResponse" xmlns="">
    <groupTable>
      <colHeading>Group Id</colHeading>
      <colHeading>Group Name</colHeading>
      <colHeading>User Limit</colHeading>
        <row>
          <col>OAL000000GRP1</col>
          <col/>
          <col>200</col>
        </row>
    </groupTable>
  </command>
</BroadsoftDocument>

What Am I doing wrong?

**Comment by nigelm** [comment]
For better or worse, I went with the convention that all attributes are snake case rather than the Broadworks Java style.

So I think, without having tested it, that your issue is that:-

```
    for group in groups.groupTable:
        print(group.groupTable)
```

should be

```
    for group in groups.group_table:
        print(group.group_id)
```

(also, in general don't set the session_id in setup - it will be set to a random one - if you force it to a set one you risk confusing Broadworks by having sessions with the same id.  I do that in testing, but thats only for testing).
