### ISSUE TITLE
no class for type phoneNumber

### ISSUE THREAD

**Issue by kikohnl** [nigelm/broadworks_ocip#4]
*R21SP1 and R24
* Python 3.8.5
* Ubuntu 20.04.2

### Description
Am I missing something here?

GroupDnUnassignListRequest among other api's use phoneNumber as a type, there is no phoneNumber class in type.py

class GroupDnUnassignListRequest(OCIRequest):
    _ELEMENTS = (
        E("service_provider_id", "serviceProviderId", str, is_required=True),
        E("group_id", "groupId", str, is_required=True),
        E("phone_number", "phoneNumber", str, is_array=True),
        E("dn_range", "dnRange", OCI.DNRange, is_complex=True, is_array=True),
    )

    service_provider_id: str = Field(type=str, required=True, mutable=False)
    group_id: str = Field(type=str, required=True, mutable=False)
    phone_number: "List[str]" = Field(type=list, required=False, mutable=False)
    dn_range: "List[OCI.DNRange]" = Field(type=list, required=False, mutable=False)

### What I Did
def GroupDnUnassignListRequest(sp, grp, dn):
    try:
        api.command("GroupDnUnassignListRequest", service_provider_id=sp, group_id=grp,
            phone_number=[api.get_type_object("phoneNumber",phone_number=dn)],)

        return True

def main()
    ServiceProvider="L000006"
    Group="OAL000006GRP1"
    DN="+1-7025551212"
    GroupDnUnassignListRequest(ServiceProvider, Group, DN)

Unknown command requested - phoneNumber
Traceback (most recent call last):
  File "deltn.py", line 86, in <module>
    main()
  File "deltn.py", line 75, in main
    result = GroupDnUnassignListRequest(ServiceProvider, Group, DN)
  File "deltn.py", line 37, in GroupDnUnassignListRequest
    phone_number=[api.get_type_object("phoneNumber",phone_number=dn)],)
  File "/home/kotis/broadworks_ocip/broadworks_ocip/api.py", line 162, in get_type_object
    cls = self.get_type_class(command)
  File "/home/kotis/broadworks_ocip/broadworks_ocip/api.py", line 141, in get_type_class
    raise e
  File "/home/kotis/broadworks_ocip/broadworks_ocip/api.py", line 138, in get_type_class
    cls = self._despatch_table[command]
KeyError: 'phoneNumber'

**Comment by kikohnl** [comment]
here is the code, one of the samples does work UserDeleteRequest, the other two do not :+1: 
#!/usr/bin/env python3
import argparse
import sys

from broadworks_ocip import BroadworksAPI
from broadworks_ocip.exceptions import OCIErrorResponse

# Authenitcaion parameters
#
BASIC_API_PARAMS = {
    "host": "IRL",
    "username": "User",
    "password": "Pass",
    "port": 2208,
}

api = BroadworksAPI(**BASIC_API_PARAMS)

def UserDeleteRequest(tn):
    try:
        api.command("UserDeleteRequest", user_id=tn)

        return True

    except OCIErrorResponse:
        print("Unable to delete user {}, Error is {}".format(tn,OCIErrorResponse))


def GroupDnUnassignListRequest(sp, grp, dn):
    try:
        api.command("GroupDnUnassignListRequest", service_provider_id=sp, group_id=grp,
            phone_number=[api.get_type_object("phoneNumber",phone_number=dn)],)

        return True

    except OCIErrorResponse:
        print("Unable to unassgign TN from group {}, Error is {}".format(sp, grp, dn, OCIErrorResponse))

def ServiceProviderDnDeleteListRequest(sp,grp, dn):
    try:
        api.command("ServiceProviderDnDeleteListRequest", service_provider_id=sp, group_id=grp,
            phone_number=[api.get_type_object("phoneNumber",phone_number=dn)],)

        return True

    except OCIErrorResponse:
        print("Unable to delete TN from enterprise {}, Error is {}".format(dn, OCIErrorResponse))


def main():

    ServiceProvider="L000006"
    Group="OAL000006GRP1"
    TN="7025551212"
    DN="+1-7025551212"

    # delete the user
    # This works! 
    result = UserDeleteRequest(TN)
    if result==True:
        print("User {} deleted".format(TN))

    # remove the TN from the Group
    result = GroupDnUnassignListRequest(ServiceProvider, Group, DN)
    if result == True:
        print("DN removed from the Group {}".format(DN))

    # remove the TN from the Enterprise
    result = ServiceProviderDnDeleteListRequest(ServiceProvider, Group, DN)
    if result==True:
        print("DN removed from enterprise {}".format(DN))


if __name__ == "__main__":
    main()

**Comment by kikohnl** [comment]
`#!/usr/bin/env python3
import argparse
import sys

from broadworks_ocip import BroadworksAPI
from broadworks_ocip.exceptions import OCIErrorResponse

# Authenitcaion parameters
#
BASIC_API_PARAMS = {
    "host": "IRL",
    "username": "User",
    "password": "Pass",
    "port": 2208,
}

api = BroadworksAPI(**BASIC_API_PARAMS)

def UserDeleteRequest(tn):
    try:
        api.command("UserDeleteRequest", user_id=tn)

        return True

    except OCIErrorResponse:
        print("Unable to delete user {}, Error is {}".format(tn,OCIErrorResponse))


def GroupDnUnassignListRequest(sp, grp, dn):
    try:
        api.command("GroupDnUnassignListRequest", service_provider_id=sp, group_id=grp,
            phone_number=[api.get_type_object("phoneNumber",phone_number=dn)],)

        return True

    except OCIErrorResponse:
        print("Unable to unassgign TN from group {}, Error is {}".format(sp, grp, dn, OCIErrorResponse))

def ServiceProviderDnDeleteListRequest(sp,grp, dn):
    try:
        api.command("ServiceProviderDnDeleteListRequest", service_provider_id=sp, group_id=grp,
            phone_number=[api.get_type_object("phoneNumber",phone_number=dn)],)

        return True

    except OCIErrorResponse:
        print("Unable to delete TN from enterprise {}, Error is {}".format(dn, OCIErrorResponse))


def main():

    ServiceProvider="L000006"
    Group="OAL000006GRP1"
    TN="7025551212"
    DN="+1-7025551212"

    # delete the user
    # This works! 
    result = UserDeleteRequest(TN)
    if result==True:
        print("User {} deleted".format(TN))

    # remove the TN from the Group
    result = GroupDnUnassignListRequest(ServiceProvider, Group, DN)
    if result == True:
        print("DN removed from the Group {}".format(DN))

    # remove the TN from the Enterprise
    result = ServiceProviderDnDeleteListRequest(ServiceProvider, Group, DN)
    if result==True:
        print("DN removed from enterprise {}".format(DN))


if __name__ == "__main__":
    main()`

**Comment by nigelm** [comment]
I don't have the facilities available to test destructive commands at present, however, untested, I think you have go the dn_range type wrong.

dn_range is:-
```python
dn_range: "List[OCI.DNRange]"
```

Thats one of the OCI Types:-

```python
class DNRange(OCIType):
    """
    Directory number range.

    The minimum and maximum values are inclusive.

    Attributes:
        min_phone_number: minPhoneNumber
        max_phone_number: maxPhoneNumber
    """

    _ELEMENTS = (
        E("min_phone_number", "minPhoneNumber", str, is_required=True),
        E("max_phone_number", "maxPhoneNumber", str, is_required=True),
    )

    min_phone_number: str = Field(type=str, required=True, mutable=False)
    max_phone_number: str = Field(type=str, required=True, mutable=False)
```

So you need to change:-
```python
 phone_number=[api.get_type_object("phoneNumber",phone_number=dn)],)
```
to
```python
 phone_number=[api.get_type_object("DNRange",min_phone_number=dn,max_phone_number=dn)],)
```

Hope that helps...
Unfortunately I can't see a way I can make this sort or thing easier without needing to give people a course on how the Broadworks OCIP stuff fits together.

**Comment by kikohnl** [comment]
I use ComPilot and look at the PSLog on the AS  to see what XML is being sent/returned.
This is why I was trying to use the phoneNumber:

<?xml version="1.0" encoding="ISO-8859-1"?>
<BroadsoftDocument protocol="OCI" xmlns="C" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<userId xmlns="">Keith.Otis.System</userId>
  <command xsi:type="GroupDnUnassignListRequest" xmlns="">
    <serviceProviderId>L000006</serviceProviderId>
    <groupId>OAL000006GRP1</groupId>
    <phoneNumber>+1-7025551212</phoneNumber>
  </command>
</BroadsoftDocument>

Your change looks like it should work but throws a TypeError:

Traceback (most recent call last):
  File "deltn.py", line 86, in <module>
    main()
  File "deltn.py", line 75, in main
    result = GroupDnUnassignListRequest(ServiceProvider, Group, DN)
  File "deltn.py", line 36, in GroupDnUnassignListRequest
    api.command("GroupDnUnassignListRequest", service_provider_id=sp, group_id=grp,
  File "/home/kotis/broadworks_ocip/broadworks_ocip/api.py", line 365, in command
    self.send_command(command, **kwargs)
  File "/home/kotis/broadworks_ocip/broadworks_ocip/api.py", line 220, in send_command
    xml = self.get_command_xml(command, **kwargs)
  File "/home/kotis/broadworks_ocip/broadworks_ocip/api.py", line 203, in get_command_xml
    return cmd.build_xml_()
  File "/home/kotis/broadworks_ocip/broadworks_ocip/base.py", line 329, in build_xml_
    self.etree_sub_components_(element)  # attach parameters etc
  File "/home/kotis/broadworks_ocip/broadworks_ocip/base.py", line 102, in etree_sub_components_
    self.etree_sub_element_(element, sub_element, subvalue)
  File "/home/kotis/broadworks_ocip/broadworks_ocip/base.py", line 167, in etree_sub_element_
    elem.text = value
  File "src/lxml/etree.pyx", line 1024, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 747, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 735, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1538, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'DNRange'

**Comment by nigelm** [comment]
Obviously I read the initial thing too quickly - hopefully the pair of test cases I have added to the end of https://github.com/nigelm/broadworks_ocip/blob/wip/tests/test_basic_command_xml.py should help.

That generates the XML appropriately - please let me know if thats not right for what the Broadworks server is expecting.

I realise that there is an argument for it failing more gracefully if command parameters are wrong - but realisitically thats fairly normal for python code.  Would be better if I could work out an easy efficient way to catch that and report it better.

**Comment by kikohnl** [comment]
Nigel,

I took what the example, does and used phone_number=[dn],) if the  dn_range is also there It deletes the phone_number and then complains it can't delete the range.

Now I can successfully delete a user, number from the group and enterprise.

This is going to significantly assist with the migrations from our Systemmetrics VoIP service where the numbers are in an enterprise trunk, and moving them to a Enterprise per customer on the same HT Broadworks platform.
 
Is there preferred way to get the error message from the OCIErrorResponese?

**Comment by nigelm** [comment]
OCIErrorResponse has OCIError as a base class.  That has message and object as properties, so something like

try:
...
except OCIErrorResponse as err:
    print(err.message)
    # returned object is err.object

**Comment by nigelm** [comment]
I believe this is complete
