### ISSUE TITLE
UserAlternateUserIdAddRequest class missing

### ISSUE THREAD

**Issue by kikohnl** [nigelm/broadworks_ocip#6]
*R24
* Python 3.8.10:
* Operating System:20.04.3

### Description

Try to add and Alternate User Id, as a requirement for provisioning Webex for Broadswords.

UserAlternateUserIdAddRequest does not exist as a class, neither do UserAlternateUserIdDeleteRequest, UserAlternateUserIdGetListRequest and UserAlternateUserIdModifyRequest

### What I Did

```
Tried to find UserAlternateUserIdAddRequest class in Requests.py. to write:

def UserAlternateUserIdAddRequest(tn, email):

```

**Comment by nigelm** [comment]
As you determined this looks likely to be a R24 addition.  Therefore it will duplicate your other issue, so I will close this.

**Comment by kikohnl** [comment]
Nigel,

This class exists in the R21 schema

Thanks,

**Comment by nigelm** [comment]
Odd - its not present in any form in the schema I have - the one included in the git repo.  I can see `UserAlternateNumbersGetRequest` (several iterations) and  `UserAlternateNumbersModifyRequest` but not those sets.

**Comment by kikohnl** [comment]
They exist my my R21 schema:

/home/kotis/ocip/Rel_21.sp1_1.551_OCISchema_All_2018-07-12/AS# sift UserAlternateUserId OCISchemaUser.xsd 
    UserAlternateUserIdAddRequest    
    UserAlternateUserIdDeleteRequest    
    UserAlternateUserIdGetListRequest    
    UserAlternateUserIdModifyRequest    
  <xs:complexType name="UserAlternateUserIdAddRequest">
  <xs:complexType name="UserAlternateUserIdDeleteRequest">
  <xs:complexType name="UserAlternateUserIdGetListRequest">
        The response is either UserAlternateUserIdGetListResponse or ErrorResponse.
  <xs:complexType name="UserAlternateUserIdGetListResponse">
        Response to UserAlternateUserIdGetListRequest.
  <xs:complexType name="UserAlternateUserIdModifyRequest">
